# Generated by Django 6.0 on 2025-12-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('team', models.CharField(max_length=50, verbose_name='隊名')),
                ('opponent', models.CharField(max_length=50, verbose_name='對手')),
                ('score_for', models.PositiveIntegerField(verbose_name='我方得分')),
                ('score_against', models.PositiveIntegerField(verbose_name='對方得分')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
